unpackaged/main/default/objects/WAMessage__c/WAMessage__c.object-meta.xml
<CustomObject>
    <label>WAMessage</label>
    <nameField>
        <displayFormat>WAM-{0000}</displayFormat>
        <label>WAMessage Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WAMessages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/WAMessage__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>WAMessages</relationshipLabel>
    <relationshipName>WAMessages</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WAMessage__c/fields/isIncoming__c.field-meta.xml
<CustomField>
    <fullName>isIncoming__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isIncoming</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/WAMessage__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/WAMessage__c/fields/Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number__c</fullName>
    <inlineHelpText>whatsapp number</inlineHelpText>
    <label>Phone Number</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/objects/WAMessage__c/fields/Read_Recipient__c.field-meta.xml
<CustomField>
    <fullName>Read_Recipient__c</fullName>
    <inlineHelpText>show current status of message.</inlineHelpText>
    <label>Read Recipient</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>delivered</fullName>
            </value>
            <value>
                <fullName>read</fullName>
            </value>
            <value>
                <fullName>sent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WAMessage__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Incoming</fullName>
            </value>
            <value>
                <fullName>Outgoing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WAMessage__c/fields/WAMid__c.field-meta.xml
<CustomField>
    <fullName>WAMid__c</fullName>
    <inlineHelpText>Whatsapp Message Id</inlineHelpText>
    <label>WAMid</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WhatsappMessageEvent__e/WhatsappMessageEvent__e.object-meta.xml
<CustomObject>
    <label>WhatsappMessageEvent</label>
    <pluralLabel>WhatsappMessageEvents</pluralLabel>
</CustomObject>

unpackaged/main/default/classes/MyWebHookListner.cls
@RestResource(urlMapping='/hookin')
global class MyWebHookListner {
	@HttpGet
    global static void doGet() {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        String verify_token = req.params.get('hub.verify_token');
        if(verify_token == 'hello'){
            res.responseBody = blob.valueOf(req.params.get('hub.challenge'));
        }
    }
    @HttpPost
    global static void doPost(){
        RestRequest req = RestContext.request;
		System.debug('req.requestBody : '+req.requestBody.toString());
        Map<String, Object> params = (Map<String, Object>) JSON.deserializeUntyped(req.requestBody.toString());
        List<Object> entrylst = (List<Object>)params.get('entry');
        Map<String, Object> entrydata1 = (Map<String, Object>) entrylst[0];
        List<Object> changeslst = (List<Object>) entrydata1.get('changes');
        Map<String, Object> changesdata1 = (Map<String, Object>) changeslst[0];
        Map<String, Object> valuedata = (Map<String, Object>) changesdata1.get('value');
        if(valuedata != null && valuedata.get('messages') != null){
        	List<Object> msglst = (List<Object>) valuedata.get('messages');
            //List<Object> msglst = (List<Object>)valuedata.get('messages');
            Map<String, Object> msgdata = (Map<String, Object>) msglst[0];
            //Map<String, Object> from_num = (Map<String, Object>) msgdata.get('from');  //from number
            String from_num = (String) msgdata.get('from');
            String wamsgid = (String) msgdata.get('id');
            Map<String, Object> textdata = (Map<String, Object>) msgdata.get('text');
            //Map<String, Object> msg_text = (Map<String, Object>) msgdata.get('body');  //message text
            String msg_text = (String) textdata.get('body');
            System.debug('from number is: '+ from_num);
            System.debug('message text is: '+msg_text); 
            String fromNumWithCode =  from_num.substring(2, 12);
            System.debug('from number is: '+fromNumWithCode);
            List<Contact> lstContact = [SELECT Id FROM Contact WHERE (Phone =:from_num OR MobilePhone=:from_num OR HomePhone=:from_num OR OtherPhone=:from_num OR AssistantPhone=:from_num) OR Phone =:fromNumWithCode LIMIT 1];
            
            if(lstContact != null && lstContact.size()> 0){
                WAMessage__c wamsg = new WAMessage__c();
                wamsg.Message__c=msg_text;
                wamsg.Type__c='Incoming';
                wamsg.isIncoming__c = true;
            	wamsg.Contact__c=lstContact.get(0).Id;
                wamsg.WAMid__c = wamsgid;
                wamsg.Phone_Number__c = fromNumWithCode;
				insert wamsg;
                
                WhatsappMessageEvent__e event = new WhatsappMessageEvent__e(RecordId__c = lstContact.get(0).Id);
                Database.SaveResult result = EventBus.publish(event);
            }
        }
        else if(valuedata != null && valuedata.get('statuses') != null){
            List<Object> statuseslist = (List<Object>) valuedata.get('statuses');
            Map<String, Object> statusdata = (Map<String, Object>) statuseslist[0];
            String current_status = (String) statusdata.get('status');
            String wamsgid = (String) statusdata.get('id');
            System.debug('current status is: '+current_status);
            List<WAMessage__c> wamsglist = [SELECT Id FROM WAMessage__c WHERE WAMid__c=:wamsgid LIMIT 1];
            List<WAMessage__c> l1 = new List<WAMessage__c>();
            for(WAMessage__c wamsgone: wamsglist){
                wamsgone.Read_Recipient__c = current_status;
                l1.add(wamsgone);
            }
            update l1;
        } 
    }
}